### ISSUE TITLE
How to use TypeScript with AngularJS 1.x

### ISSUE THREAD

**Issue by dawud-tan** [tomastrajan/component-pattern-for-angular-js-1-x#1]
is it possible to use TypeScript with this example?

**Comment by tomastrajan** [comment]
Yes, I actually started with typescript version but then I switched back to ES6. Mainly because I wanted to maintain the same module syntax for all imports and exports. The problem was that importing of CSS and templates didn't work that well together with Webpack. When using ES6 I can import templates and CSS using `import` syntax.

That being said, what you can do is to add `ts-loader` in the webpack configuration for the `.ts` files and switch to `require('my-template.html')` syntax for templates and CSS, this than works as expected.
